### ISSUE TITLE
thread_id implicit relationship to message id semantics

### ISSUE THREAD

**Issue by devin-fisher** [decentralized-identity/didcomm-messaging#132]
The language for thread_id relationship is stronger than the same Aries RFC's language. This language states that the thread_id must always start out as message id. Instead of the implicit relationship in the Aries RFC where if not specified it is implicitly defined as the message id.

```thread_id - OPTIONAL. Identifier for the current protocol's thread. The thread_id attribute value MUST be equal to the id of the message that initiated the protocol. All messages are part of a thread. If thread_id is not present, the thread for the message is identified by id.```

Question: is this change intentional? 

Suggested change to the language: 
```If the thread_id is defined, the thread_id is the value given. But if the thread_id is not defined, the thread_id is implicitly defined as the id of the given message and that message is the first message of a new thread.```

**Comment by dhh1128** [comment]
I suggested that Devin open this ticket, and I wanted to add a little color about why.

We have found in certain situations that it is desirable to create the code object for a thread before we create the code object for a message (e.g., we know we're going to have a conversation with a remote party, but we're not ready to do it yet). In such cases, it's nice to have the values of the IDs for thread and message be independent, because the IDs for these two objects are created at different times, in different places in code.

We can conform to this new verbiage if we must, but it introduces stronger temporal coupling and stronger logical coupling than we want. And it seems unnecessary. Hence the ticket.
