### ISSUE TITLE
RFC 0021 - Encoding byte for content type of envelope and content messages

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/didcomm-messaging#19]
Original Issue: https://github.com/hyperledger/aries-rfcs/issues/77

**Comment by kdenhartog** [comment]
After thinking about transports for quite some time, this functionality seems better handled by a mime-type from the transport. Some reasons why:

1. Relying on the transport to describe the message syntax doesn't change the security properties.
2. Self encapsulating this into the payload itself makes it more painful to parse and unpack the message.
3. Realistically, support for a transport has to be documented so that we all do it in the same way, so document how the message format should be communicated isn't changing much.
4. It changes the mental model in a way that makes it easier for us to reason about and address privacy concerns that emerge from unique implementation patterns once they arise.

**Comment by TelegramSam** [comment]
Not all transports have a mime-type header. For those without (like websockets) we'd need to come up with extra metadata to contain this type of info.

**Comment by dhh1128** [comment]
I agree with Sam. I don't feel comfortable with the MIME type solution unless we can explain to ourselves how we solve the problem over raw sockets, bluetooth, SMTP, etc -- and our explanation doesn't sound like an inconsistent mess.

**Comment by kdenhartog** [comment]
I've got a few thoughts that may come off a bit convoluted througout this message, but I wanted to get my initial thoughts out there so you both could think on it and we can discuss further on a call.

Parsing bytes off a JSON message leads to complications in implementations from what I've identified. For me it was very strange, and while I haven't validated this, I'd highly suspect this would cause many server implementations to cause problems because of a random byte on the front. Has anyone tried this before in previous work? I haven't but it's definitely something I will have to do before I feel prepending bytes on are the right path. On a hunch right now, I suspect encapsulating the message and the 

For what it's worth, I'm not caught on the idea of it must be done via MIME-types as defined in RFC 1341, but rather that I'm looking for some aspect that exists at the transport layer that I can use to indicate the format of the content. In HTTP(S) that's a mime-type, in Websockets that could be [protocols](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket) or [extensions](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/extensions), and in Bluetooth it could be the type section of the Header in the Bluetooth packet format. In raw bytes, well at that point you're literally just defining a full on protocol at that point, so we'd need to be sure to define how the bytes would work.

In any case, the two principal requirements I'd like us to adhere to is:

1. the envelope format MUST be indicated via the transport layer.
2. A supported transport MUST be defined in a Transport Layer specification that indicates how the transport is used and complied with.
3. Support for transport layers MUST be verifiable in the test suite.

The reasoning behind 1 is because I believe the use of self encapsulated bytes being prepended to JSON makes for a messy situation that I don't want to have to implement or debug.

The reason for 2 and 3 is because it will produce better interoperability results.

Ultimately, what I'm objecting to is the use of prepended bytes onto JSON content because I believe that's going to be a headache to implement and will lead to debugging headaches and even potentials interoperability concerns.

**Comment by dhh1128** [comment]
I'm aligned with Kyle's comment above in this respect: we should not put prepended bytes onto JSON.

I am strongly opposed to any approach where I cannot easily and algorithmically determine the content type from the content itself. I reconcile that position against what I also said about not prepending bytes onto JSON by observing that that the byte that signals the presence of JSON could be the opening curly brace, `{`. That doesn't prepend anything. If you don't see that byte, then something else is at play.

>1. the envelope format MUST be indicated via the transport layer.

I'm emphatically against ONLY indicating content type in the transport layer, but I might be talked into ALSO indicating content type in the transport layer, redundantly.

The problem here is that pipes aren't supposed to care whether the liquid inside them is water or oil. It's not their concern. Mixing content type into transport invites many other leaky abstractions that are problematic. I don't agree with Kyle's prediction that self-encapsulation is messy (though I do agree that if it required prepending bytes to JSON, it would be messy).

>2. A supported transport MUST be defined in a Transport Layer specification that indicates how the transport is used and complied with.

Okay. No pushback.

>3. Support for transport layers MUST be verifiable in the test suite.

Also no pushback.

**Comment by kdenhartog** [comment]
> I'm emphatically against ONLY indicating content type in the transport layer, but I might be talked into ALSO indicating content type in the transport layer, redundantly.

I can work with that compromise. Let's discuss this on the next call. While I think developer experience is important, I think it's also important to consider the ease of processing messages when they come off the pipe so that we don't setup architectures that are more susceptible to DDoS and Spam attacks.

**Comment by TelegramSam** [comment]
Closed in WG Meeting 2020-11-02.
