### ISSUE TITLE
Any reference implementation of ECDH-1PU?

### ISSUE THREAD

**Issue by vimmerru** [decentralized-identity/didcomm-messaging#216]
Hi,

The key crypto in spec is ECDH-1PU. I looked most popular jose libraries and didn't find any ECDH-1PU implementations. 

Also i looked to mentioned implementations of DID Comm v2 and didn't find anything related to ECDH-1PU. Seems all use ECDH-EC only that contradicts the spec. 

Is there any proven ECDH-1PU implementation available?

**Comment by OR13** [comment]
@tplooker @Baha-sk both have implementations they can link to.

**Comment by Baha-sk** [comment]
I believe the list was recently added in the main readme [here](https://github.com/decentralized-identity/didcomm-messaging#implementations)

**Comment by vimmerru** [comment]
@Baha-sk Thanks. Seems i missed aries-go https://github.com/hyperledger/aries-framework-go/pull/2841

**Comment by dhh1128** [comment]
@vimmerru : The following google doc has notes about ECDH-1PU, including links to a number of implementations: https://docs.google.com/document/d/1418pgfXfhxLPXYXugADndwSQeMeFyAeEX81nz50-7Ps/edit

However, all of the implementations that it links are implementations of Draft 3 of the ECDH-1PU RFC; I believe only the Go Framework codebase has an impl of Draft 4.

**Comment by Baha-sk** [comment]
That's correct @dhh1128 for the Go implementation of ECDH-1PU. We were able to build an [interop test](https://github.com/hyperledger/aries-framework-go/blob/main/pkg/doc/jose/encrypter_decrypter_test.go#L1452) decrypting the JWE of appendix B example of [draft4](https://datatracker.ietf.org/doc/html/draft-madden-jose-ecdh-1pu-04#appendix-B.11).

Implementations of draft3 should upgrade since it's stale. They need to upgrade to draft4 because it uses the encryption tag as part of key wrapping/kdf to provide sender authenticity (ie: non-redpudiance message to the recipients only) and prevents a malicious recipient from impersonating the sender by reusing the same tag/iv/epk.

**Comment by kdenhartog** [comment]
@vimmerru are you satisfied with the answer to this? If so please close this issue.

**Comment by vimmerru** [comment]
One more implementation here https://github.com/hyperledger/aries-askar/blob/main/askar-crypto/src/kdf/ecdh_1pu.rs 

I think we can close the ticket. Thanks for the answers.
