### ISSUE TITLE
Need details about invalid curve and weak point attack resistance

### ISSUE THREAD

**Issue by dhh1128** [decentralized-identity/didcomm-messaging#217]
The section about key negotiation specifies an algorithm, but not best practices for using it. Without additional guidance, DIDComm could be vulnerable to the same sort of theoretically-correct-but-practically-flawed implementations that caused this well known article to be written:

https://www.infoworld.com/article/3184582/critical-flaw-alert-stop-using-json-encryption.html

**Comment by dhh1128** [comment]
Tagging @vimmerru

**Comment by kdenhartog** [comment]
Definitely a concern here for NIST curves. Point compression helps, but due to the way JWKs require `x` and `y` coordinates for NIST curves it's still a concern for implementations.

Suggested outcome for this is that Yolan or myself write a security section paragraph on this topic to cover what needs to be done to prevent it. 

@nielmadden has written an excellent [blog post ](nielmadden) on the topic which points to normative references we can use in the paragraph if someone else wants to take a stab at it as well.
