### ISSUE TITLE
need repeatable methodology for new transports

### ISSUE THREAD

**Issue by dhh1128** [decentralized-identity/didcomm-messaging#222]
We have info about how we do DIDComm over HTTP. I want a recipe for how to write up instructions for new transports. Are these instructions called a "note", and "extension", a "transport plugin", or what? Where do I publish one, and what should it contain?

The most substantial effort like this that I know about is [the one for BLE](https://github.com/decentralized-identity/didcomm-bluetooth/blob/main/spec.md). I want to do another for SMTP, another for raw sockets, another for NFC, and another for SMTP.

**Comment by dhh1128** [comment]
Any advice or thoughts, @TelegramSam ?

**Comment by kdenhartog** [comment]
So far we've defined HTTP and Websockets in [section 17](https://identity.foundation/didcomm-messaging/spec/#transports) of the spec. I think we may want to define what is necessary to define a new transport in that section. 

> Are these instructions called a "note", and "extension", a "transport plugin", or what?
"Note" in my mind is likely wrong. In W3C terms that usually means it's non-normative (doesn't mean we need to keep that terminology here though)

"Extension", seems like it could make sense because a transport will need to be normative, but not necessarily required for usage.

"Transport Plugin" also seems like it would be a good option here to elevate the meaning to avoid confusing the purpose of the extensions at this point.

> Where do I publish one, and what should it contain?

I'm open to sticking with the convention of HTTP/Websockets where we define it within the specification. Given BLE has been a bit more verbose (and by extension a lot more normatively explicit which in my opinion is good) I think it may actually be better to separate these out into separate documents so that we don't overly bloat the spec with transport details.

**Comment by TelegramSam** [comment]
Extension is closest for a transport. The sizable gap between the Bluetooth transport details is interesting and notable, and likely justifies a different document at least at this point. I think new transports can be added without modification of the spec, outside of the normative ones already included.

It is worth noting that QR codes are kind of a transport (though really just an encoding for such), and NFC will likely fall into the same category.

**Comment by kdenhartog** [comment]
Based on @dhh1128 comment #220 as well I think it's correct to say URIs are a transport layer in their own right as well.

**Comment by kdenhartog** [comment]
Needs discussion on a call about what are the minimum requirements we want to be defined for a transport.

The few that pop to mind for me are:
How it's encoded
How is the type communicated

**Comment by TelegramSam** [comment]
Also, what typical conventions in the transport mean in the context of DIDComm. Example is HTTP status codes.

**Comment by awoie** [comment]
The following might sound probably controversial but I'm wondering how those changes resonate with people in this group.

IMO, it would help if we would restructure the protocols and transports section a bit a fix a couple of issues... 

Each transport MUST define:
- format of `serviceEndpoint` -> could be a URI or an object (also according to DID spec)
- how to actually send messages, e.g., through HTTP POST, through dial protocol (libp2p), etc.
- how mime-types of the content are provided, e.g., through Content-Type header, etc.

Make OOB (invitation) a protocol rather than a standalone section.

Then, make a CORE protocols section with the following sub-sections:
1. Invitation (OOB)
2. Discovery
3. Trust ping
4. + others if required (I don't see any yet)

In the protocols section, we should say that each protocol MUST define:
- requires sender anonymity OR sender authentication
- types of sender authentication, i.e., repudiable vs non-repudiable, although if not specified MUST default to authcrypt. Note, the invitation protocol likely does not require any protection.
