### ISSUE TITLE
The approach for backward compatibility

### ISSUE THREAD

**Issue by vimmerru** [decentralized-identity/didcomm-messaging#224]
Hi,

Just imagine the following scenario

- Alice agent is written based on few month ago specification and ECDH-1PU v3 draft
- Bob agent is written based on current specification and ECDH-1PU v4 draft

Is there any way they can communicate? What if ECDH-1PU v4 will be deprecated? What to do with current agents?

**Comment by Baha-sk** [comment]
Thanks @vimmerru. This is a valid concern, but we don't want to support any 1PU revision prior to v4.

For future versions, if any arises, we will need to create a new envelope type (media type, ie `typ` protected header) reflecting the new version to help implementations detect it. But this type of spec are meant to be pretty much fixed, unless a vulnerability is found, like v3 sender impersonation vulnerability that was addressed in v4. Luckily for us, implementations are still pretty recent, it's easier to upgrade to v4 now since we're not in prod yet.  

For now the media type value to be set in `typ` header for 1PU is `application/didcomm-encrypted+json` as per the DIDComm Encrypted Message [section](https://github.com/decentralized-identity/didcomm-messaging/blob/master/docs/spec-files/message_structure.md#didcomm-encrypted-message) of the specs.

I would say based on the nature of newer versions updates we will see if version compatibility is feasible. But old agents will either need to be upgraded or support only the version of the software implementation they're currently running if/when a new 1PU version is released.

**Comment by dhh1128** [comment]
I agree that 1PU versions prior to draft 4 do not need to be supported. Impls of that were experimental and are expecting to be upgraded before any production use, I believe.

Baha has done quite a bit of work on this topic to deal with the issue of an orderly upgrade path between DIDComm v1 and DIDComm v2. Having an agent using v1 talk to an agent using v2 appears unrealistic, so we've ruled it out. But we have laid the foundation to at least *detect* which version of DIDComm an agent is talking. And I agree with Baha that the basis for making decisions will be variations on the `applicaiton/didcomm-encrypted+json` value. We'll have to introduce a new value for that, and react to it.

**Comment by kdenhartog** [comment]
In regards to @vimmerru initial question, this should be detectable based on the `enc` property in this case because we're forced to change the cipher algorithm, we can detect usage of V3 vs V4. In the future, it will depend heavily on the change to the draft so we'll have to address these things on a case by case basis.

As @dhh1128 pointed out we can look to our media-types as a potential method or some other trickier methods like private headers in the protected JWE portion to fix it (less preferred IMO).

**Comment by ashcherbakov** [comment]
It looks like the current spec assumes compatibility by using profiles: https://identity.foundation/didcomm-messaging/spec/#negotiating-compatibility
So, the questions are 
1) What if no profile is set (`accept` field is empty, which is possible according to the spec)? How Alice should tell Bob what profile (DID Comm version) she wants to use? How they can negotiate the version of the DID Comm in this case?
2) Do I understand correctly, that it's assumed currently that we will have to increment a major version in the protocol semver every time when
 - a new algorithm or a new curve needs to be supported 
 - a non-compatible fix in the algorithm is done (like in ECDH-1PU v3 VS v4).
 I think we need to mention in the spec more explicitly how the spec should evolve, regarding this items.

**Comment by kdenhartog** [comment]
Good questions, I'm probably going to lean towards the ways QUIC/TLS handles this because they're working solutions. I'll have to get back on the details though once I've done a bit more research into how they handle it.

**Comment by dhh1128** [comment]
I agree that the spec needs more detail about what constitutes a major revision. I also agree that a non-compatible fix is definitely a major revision.

Regarding the addition of a new algorithm or new curve: just adding this isn't what triggers a major rev -- making it a *required* feature of a protocol is what triggers a major rev.

**Comment by vimmerru** [comment]
> Regarding the addition of a new algorithm or new curve: just adding this isn't what triggers a major rev -- making it a required feature of a protocol is what triggers a major rev.

I think triggering major version ins't just solution for backward compatibility for widely adopted transport-level protocol. Keeping in mind history of TLS the approach on how to communicate with outdated client is quite important. 

I am not sure we have a feasible solution for asynchronous protocol without agreement phase.

**Comment by vimmerru** [comment]
Partially the solution can be definition of key negotiation process based on analysis of DID Doc, but it must be carefully analysed.

**Comment by AnomalRoil** [comment]
This is akin to asking "how agile are we" I feel...

And my first reaction is obviously that we should be as agile as we can, but at the same time being too agile can also complicate things severely. 

It should be easy to "switch" crypto scheme, curves or security levels if future research is discovering new attacks that require us to do so...
But requiring backward compatibility with old versions of a protocol is pretty rare and not necessarily desirable IMO as it's going to lead to codebases full of legacy stuff like OpenSSL...

That being said, we have language discussing the SemVer of DIDComm in the spec, but it seems we currently are not providing the version used in a DIDComm message. 

(An easy workaround might be to include that in the `cty` field since we are not using it currently, but is the version used really structural information about the JWT?)

**Comment by dhh1128** [comment]
Discussed with @TelegramSam on a phone call.

We feel that it's important to be able to detect the type of the plaintext by examining the ciphertext. In the future, this might involve adding a plaintext version hint to the media type of the encrypted text, for example. But right now, we will use the *absence* of such a clarifier as an indicator that the plaintext is aligned with this version of the spec. This forces the next version of the spec, that creates a new form of plaintext, to solve the problem.

**Comment by dhh1128** [comment]
(So that's a vote to defer this for v2)

**Comment by mccown** [comment]
@dhh1128, I'm not sure I understand the context of "detect the type of the plaintext by examining the ciphertext".  

Backwards compatibility is a challenge.  What about adding an algorithm identifier to let the receiver determine whether they want to accept / process a message or not  (it's late, so this quote comes to mind, "It's an older code, sir, but it checks out.  I was about to clear them." 😉)

The algorithm version ID could also address @AnomalRoil 's comment about easily switching crypto as needed.  

As I'm writing, I'm thinking of a number of issues that we may want to discuss, so I'm also in favor of deferring.

**Comment by TelegramSam** [comment]
Proposed spec text "Future work that changes assumptions and fixed decisions in this spec MUST also provide an unambiguous distinction between this work and the changes of the new work. Care should be taken to avoid exposing information outside the encrypted section of any message to protect attacks from traffic analysis."

**Comment by TelegramSam** [comment]
Discussed WG 20220502.
The above proposed text is already inferred. We've decided to not address the issue directly, and leave those specifications to future work.
