### ISSUE TITLE
Is `anoncrypt(sign)` allowed?

### ISSUE THREAD

**Issue by vimmerru** [decentralized-identity/didcomm-messaging#242]
Specification here https://identity.foundation/didcomm-messaging/spec/#anonymous-encryption says

> Use of Anonymous Encryption SHOULD NOT be paired with a method of message authentication other than Authenticated Encryption as defined in this specification. Further discussion of message authentication can be found in the Implementation Guide.

Is it correct sentence?

**Comment by kdenhartog** [comment]
The general consensus was that this would be discouraged but we couldn't outright ban it from what I remember because it was untestable. This language made it in based on @TelegramSam feedback that it would help to discourage it. There was an issue either here or on WACI between @dhh1128 and @OR13 that discussed the topic, but I'm unable to dig it up right now.

**Comment by TelegramSam** [comment]
We want to discourage people from routing around authenticated encryption by using a signed and anoncrypted message in its place. This eliminates repudiation, which is a required feature. (Non-repudation can be added, but never removed.)

The better form of this is authcrypt(sign(message))

Right now ECDH-ES 'feels' more desirable because of broader library support, but I'm hoping that decreases as ECDH-1PU library support increases.

**Comment by kdenhartog** [comment]
@vimmerru Do you have any follow up questions you want to ask based on those answers? If not and you feel satisfied with this could you close the issue?

**Comment by vimmerru** [comment]
@kdenhartog I still think possible layers with clearly defined use cases should be added to specification, but for this concrete question i believe i am ok.
