### ISSUE TITLE
Signed message serialization syntax

### ISSUE THREAD

**Issue by asmarty** [decentralized-identity/didcomm-messaging#254]
Should the signed message syntax be [General](https://datatracker.ietf.org/doc/html/rfc7515#section-7.2.1) or [Flattened](https://datatracker.ietf.org/doc/html/rfc7515#section-7.2.2)?

General Syntax example: 
```JSON
{
   "payload":"eyJpc3MiOiJqb2UiLA0KICJleHAiOjEzMDA4MTkzODAsDQogImh0dHA6Ly9leGFtcGxlLmNvbS9pc19yb290Ijp0cnVlfQ",
   "signatures":[
      {
         "protected":"eyJhbGciOiJSUzI1NiJ9",
         "header":{
            "kid":"2010-12-29"
         },
         "signature":"cC4hiUPoj9Eetdgtv3hF80EGrhuB__dzERat0XF9g2VtQgr9PJbu3XOiZj5RZmh7AAuHIm4Bh-0Qc_lF5YKt_O8W2Fp5jujGbds9uJdbF9CUAr7t1dnZcAcQjbKBYNX4BAynRFdiuB--f_nZLgrnbyTyWzO75vRK5h6xBArLIARNPvkSjtQBMHlb1L07Qe7K0GarZRmB_eSN9383LcOLn6_dO--xi12jzDwusC-eOkHWEsqtFZESc6BfI7noOPqvhJ1phCnvWh6IeYI2w9QOYEUipUTI8np6LbgGY9Fs98rqVt5AXLIhWkWywlVmtVrBp0igcN_IoypGlUPQGe77Rw"
      }
   ]
}
```

Flattened Syntax example: 

``` JSON
{
   "payload":"eyJpc3MiOiJqb2UiLA0KICJleHAiOjEzMDA4MTkzODAsDQogImh0dHA6Ly9leGFtcGxlLmNvbS9pc19yb290Ijp0cnVlfQ",
   "protected":"eyJhbGciOiJFUzI1NiJ9",
   "header":{
      "kid":"e9bc097a-ce51-4036-9562-d2ade882db0d"
   },
   "signature":"DtEhU3ljbEg8L38VWAfUAqOyKAM6-Xx-F4GawxaepmXFCgfTjDxw5djxLa8ISlSApmWQxfKTUJqPP3-Kg6NU1Q"
}
```

**Comment by brianorwhatever** [comment]
I asked this question (re: encrypted message but same idea I would think) on the [WACI-Pex call today](https://us02web.zoom.us/rec/share/Fo71hRFTXnHHaWhBN-btVGVbON2SloiGO0oP-bGz7R3OIsLSAOj3PmddP1gE1dk.212hZWjrYdqHbIhu) and was told the General syntax should be used. 

On the encryption side his allows for the possibility of encrypting to multiple recipients.

If the above is in fact true for both signing and encrypting there should be normative text added to the spec.

**Comment by asmarty** [comment]
Does it mean one signed message can have several signatures by spec?

**Comment by AnomalRoil** [comment]
Being given the fact that the DID ecosystem is often containing clues that "threshold signatures" might be used, I'd say it's best to assume multiple signatures (partial signatures in the case of threshold signing) should be supported, because then we could have a message that needs to be signed by a threshold number of parties, thus containing multiple signatures.

**Comment by vimmerru** [comment]
> Being given the fact that the DID ecosystem is often containing clues that "threshold signatures" might be used, I'd say it's best to assume multiple signatures (partial signatures in the case of threshold signing) should be supported, because then we could have a message that needs to be signed by a threshold number of parties, thus containing multiple signatures.

I started to completely loose idea of DID Comm if it is really use case. I think if you want some kind of voting or something similar you can put signatures inside of body. For me it looks like completely use less for "transport protocol".

**Comment by ashcherbakov** [comment]
I read the current DIDComm spec as only one signature is assumed in https://identity.foundation/didcomm-messaging/spec/#message-signing and https://identity.foundation/didcomm-messaging/spec/#didcomm-signed-message.

> A DIDComm signed message is a signed JWM (JSON Web Messages) envelope that associates **a non-repudiable signature** with the plaintext message inside it.

>  feature **a non-repudiable digital signature**

> When **verifying the signature**

> Construct a JWS with the following header: <only one kid there>

If multiple signatures are allowed/assumed, it must be clearly and explicitly said in the DIDComm spec.

I agree with Slava that other cases can be supported on the protocol level as part of the Plaintext body.

**Comment by AnomalRoil** [comment]
I feel like the specification is just not clear about that. E.g. a threshold signature is technically one signature made of multiple signatures...

I'm not saying it's desirable for DIDComm, I'm just noting that the rest of the DID ecosystem seems keen on keeping their options open.

Also we might imagine a message that's signed with two different type of keys, because of some key expiration issue, or that we might want each mediator to add their signature to the message, to ensure they've effectively forwarded it, or whatsoever. 

Limiting us to just one signature is just that: an arbitrary limitation, as far as I can tell.

Also, we mentioned "crypto agility", trying to sign stuff with both a NIST-approved scheme and a future-proof PQ-scheme might be a thing in the (near) future.

Whether there is already a usecase for multiple signatures in a DIDComm message or not, I don't know. But limiting us to one also doesn't seem like something we _need_ currently.

**Comment by dhh1128** [comment]
There is absolutely a use case for multiple signatures on DIDComm *payloads* (e.g., "Attached to this message, I am sending you a contract signed by 3 parties. Please affix your signature as well, so we cross the threshold of N=4."). However, I don't think there is a use case for multiple signatures on DIDComm *messages* themselves. A message can only have one sender, as reflected in the fact that the `from` field is a single string value, not an array. Notice that in my example, the act of sending a message wasn't partial; it was binary ("I'm sending you..."). When a DIDComm *message* is signed, the signature proves who sent the message (where "send" means to compose the plaintext and prepare it for transport by wrapping it in layers of encryption). That's always one party only. Changing this to allow for multiple senders would radically redesign DIDComm, change the way we describe some of its security and privacy guarantees, etc.

I feel like several comments in the discussion above misunderstand this distinction.

By design, the party who signs a payload (an attachment) does NOT have to be the sender of the message. In fact, the signature on a payload doesn't have to have DID-related qualities at all; it could be signed with an SSH keypair, for example. Bob could send a message to Alice, saying, "Look, here is a .deb signed by Canonical." Canonical knows nothing about DIDComm, but their signature on the payload still makes sense.

In the context of WACI-PEX, the thing that's being signed should be a JSON presentation manifest or presentation exchange request. That's a payload, not a message. If WACI-PEX wants to conflate the signer of a payload with the signer of a message (requiring the same person who "sent" the message in a DIDComm sense to be non-repudiably associated with the presentation exchange request as well), that's fine as a WACI-PEX requirement. But it doesn't mean DIDComm is going to stand on its head to put payload-level constructs into message envelope design.

Regarding crypto agility: we know we need certain kinds of crypto agility. But that does not mean it is always a virtue. Setting aside [security arguments against agility](https://paragonie.com/blog/2019/10/against-agility-in-cryptography-protocols), there is a large implementation cost (lines of code, complexity of APIs, dependencies of a library) to the agility, which is that we have to make the algorithms that process messages increasingly abstract and generic. Do we need the ability to plug in quantum-safe algorithms, sometime soon? Yes. Do we need the ability to abstract away how many parties send a message? I SERIOUSLY doubt it. And supporting it would wreak all kinds of havoc on the complexity of libraries that support DIDComm. In other words, increasing crypto agility there means decreasing programmer agility elsewhere. It's not a good tradeoff.

All of this is a long way of saying that I can't see any reason why we would want General Syntax for a DIDComm Signed Message, other than a WACI-Pex requirement that I think is ill-considered. I think WACI-Pex should be signing payloads, not messages (or should be signing payloads to authenticate who's making a request, and messages to authenticate who's providing a nonce, and then requiring them to be the same party, if that's what they want to do).

**Comment by dhh1128** [comment]
BTW, the current definition of payload signing in DIDComm uses Flattened Syntax, but externalizes the payload in Detached Mode (https://datatracker.ietf.org/doc/html/rfc7515#appendix-F). We might want to upgrade this so it uses General Syntax instead. Unless/until we do, we are not allowing multiple signatures on a single payload.

**Comment by AnomalRoil** [comment]
How do we support DID documents who's sender verification method is specifying threshold signatures then?

CorpA is requiring signatures from 3 out of 10 keys to authenticate the DID subject, CorpA wants to send you a message, how are the signatures authenticating it provided?

The "sender" field is supposedly any valid DID or DID URL and currently it seems we are expecting that: 
> Authorization of the encryption key for this DID MUST be verified by message recipient with the proper proof purposes. See the message authentication section for additional details.

So I'd expect the [message auth section](https://identity.foundation/didcomm-messaging/guide/#message-authentication) (which is empty currently) to mandate the same kind of validation of the authentcation key properties and purposes...

**Comment by dhh1128** [comment]
I agree that the message auth section needs to explain this.

>How do we support DID documents whose sender verification method is specifying threshold signatures then?

First of all, for perspective, the DID spec registry currently [lists about 90 known DID methods](https://w3c.github.io/did-spec-registries/#did-methods). I am an editor of the DID Rubric, a W3C publication examining the properties of these methods in some detail; I have personally studied maybe a dozen of these methods, and had conversations with authors of many more. AFAIK, there is not a single method that supports threshold signatures. I am aware of 2 methods that supported M-of-N policies. One is peer DIDs, and one is did:git, which has since been deprecated by its author. Peer DIDs supports M of N by making signature collection a higher-level concern, not by using group signatures or threshold signatures; that is, if you want a 3-of-10 policy with peer DIDs, you collect 3 signatures from a pool of 10 people; there is no composite signature built. (Christopher Allen, author of did:btcr, made an intriguing comment about possibly supporting them at one point, but I don't believe it's a current feature.) There is a verification method that allows composition from other methods using boolean operators, but to my knowledge it is not implemented in production anywhere.

So the question about threshold signatures is, AFAICT, entirely theoretical. The reason is not that the crypto is hard in the abstract; it's that the concept of DID control is not well enough supported yet to provide a mature foundation upon which threshold sigs can be built into a DID method. For example, many DID methods use a blockchain that wants to authenticate a DID controller before allowing updates to a DID -- yet the backing blockchain itself doesn't support M-of-N schemes.

**Comment by AnomalRoil** [comment]
I was trying to encompass M-of-N schemes when I was saying "threshold", because threshold signature themselves sometime have an aggregate signature which is just a single signature, but M-of-N sigs require M sigs... How do we do M-of-N sigs with DIDComm if we are restricted to single signature?

**Comment by andrewwhitehead** [comment]
I believe that with JWE and JWS, recipients should be able to handle both the flattened and the general syntax. Requiring senders to only use the general syntax seems like an unnecessary restriction which could limit compatibility with third party libraries.

**Comment by AnomalRoil** [comment]
I'm happy with us not restricting ourselves needlessly in any way on my side :)

**Comment by vimmerru** [comment]
> I believe that with JWE and JWS, recipients should be able to handle both the flattened and the general syntax. Requiring senders to only use the general syntax seems like an unnecessary restriction which could limit compatibility with third party libraries.

Just FUI, Then more syntax we need support than harder it will be to provide good DID comm library that support all cases. For example, there is no popular JOSE libraries on the market that supports generic json encoding. And it will be hard to support multiple recipients/signatures without big refactoring inside of these libraries that makes chances to accepted contribution low.

**Comment by brianorwhatever** [comment]
Sorry for confusing this issue with the WACI-PEX encryption example. My thoughts were re: JWE only not JWS.

I would like to see JWE general syntax as a hard requirement to ensure we can encrypt for multiple recipients.

**Comment by TelegramSam** [comment]
Messages should be signed only be the sender.
Does the presence of multiple key types for the same sender warrant multiple signatures on a sent message?

**Comment by TelegramSam** [comment]
Discussed WG 20220509. Allow both general and flattened forms, though flattened is sufficient as only one signature is useful when signing a message.
