### ISSUE TITLE
Is `body` required or optional?

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/didcomm-messaging#273]
I am not sure if the body is required and able to be blank (`{}`) or if it is optional. This isn't articulated in the spec. Trust ping protocol doesn't include it so that might mean it's optional but would like some clarification

**Comment by kdenhartog** [comment]
Personally I like the idea of it being required, but blank because it removes the code paths around handing types in typed languages a tad bit easier.

E.g. in typescript you'd move from `body?: object` being undefined and needing to be checked in code, to `body: object` where the type system can handle the miss-formatted errors for the implementer.

**Comment by brianorwhatever** [comment]
I agree and believe the majority of messages will have message specific attributes so think we should make it formal requirement.

**Comment by swcurran** [comment]
I'm not sure about this:

Is "from" required on all messages or just when establishing or changing the DID for a connection?  I had been thinking that receiving the message requires determining on what connection the message arrived, and therefore to whom the response should go.

**Comment by brianorwhatever** [comment]
@swcurran is that comment made for #271?
