### ISSUE TITLE
Where can be found published json-ld @contexts aligned with current version of DIDComm messaging proposal?

### ISSUE THREAD

**Issue by jaroslavsaxa** [decentralized-identity/didcomm-messaging#324]

**Comment by kdenhartog** [comment]
I'm pretty sure this is already being tracked over here: https://github.com/decentralized-identity/didcomm.org/issues/9

Here's where the file is located, but we need to get the didcomm.org page to properly publish it: https://github.com/decentralized-identity/didcomm.org/blob/main/docs/messaging/contexts/v2/index.json

If you can figure out how to do that and submit a PR to address it over there that would be good. Otherwise I can get around to it when I get the time.

**Comment by TelegramSam** [comment]
To be clear - The DIDComm plaintext format has nothing to do with json-ld itself. The DIDComm service endpoint to be contained within DID Documents _does_ have a relation to json-ld, and that's @kdenhartog was referring to above. 

The link @kdenhartog shared is the context file, though not currently being published to it's correct location. That is being tracked in the ticket he references as well.

**Comment by TelegramSam** [comment]
Discussed WG 20220131.
