### ISSUE TITLE
ECDH-ES question about apu and apv (from waci-pex)

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/didcomm-messaging#326]
note: https://blog.identity.foundation/ecdh-1pu-implementation/

discussed on today's WACI-PEx call (in the context of a diff signature suite, ECDH-ES ) -- @or13 was asking what libraries and how interact with them to get `apu` and `apv` into every message?    @rolsonquadras said he'd check with baha but figured maybe this group might want to chime in with any other links or ideas or anecdotes

**Comment by bumblefudge** [comment]
https://github.com/decentralized-identity/didcomm-messaging/issues/205

**Comment by OR13** [comment]
```json
{
      "ciphertext": "ozt71h4tEJJQN9obCx8pm6I1SNgWfzxlUqs5r2VRmeoB97B0O-lQnjsarI0nNnTConsv5jo2XErifc7xHS-lEZ7Yw_p1Vg",
      "iv": "Z4x3pmg07q7fQP7s",
      "recipients": [
        {
          "encrypted_key": "YEQjibgREmfkhoYcD0XJUsI4wuaCmKxj2GgaOtPMqYk0CkcIkhdLwA",
          "header": {
            "alg": "ECDH-ES+A256KW",
            "kid": "did:example:123#key-0",
            "epk": {
              "x": "Ua4qf2B-v5gq2ENXTHjXGJIoiTOjA5_KMzNYnFfu_Qo",
              "crv": "X25519",
              "kty": "OKP"
            }
          }
        },
        {
          "encrypted_key": "V9b2WfHaK-1zfSRQPi73eIsvQkHyv7b4WWoM2noVjLYAuf1_dlerOA",
          "header": {
            "alg": "ECDH-ES+A256KW",
            "kid": "did:example:123#key-1",
            "epk": {
              "x": "YLaGAnv4sMc7g5NXbzEmLXSIYs7B0knkcoJDYl0i5h4",
              "crv": "X25519",
              "kty": "OKP"
            }
          }
        }
      ],
      "tag": "c8i0EmPILd_aqX59AwzaNw",
      "protected": "eyJlbmMiOiJBMjU2R0NNIn0"
    }
 ```

**Comment by Baha-sk** [comment]
That's right, ECDH-ES (used in Anoncrypt) does not require apu/apv (they're useful to add integrity to the message as they're used in the key derivation process).

As for ECDH-1PU (Authcrypt), these are required since the sender kid (skid) can be replaced by APU (which is `b64(skid)`) if skid is missing in the headers. As for APV, the DIDcomm V2 spec explains it's the list of recipients `kid` alphabetically sorted and joined with `.`, the result is then b64 encoded. See the spec definition here: https://identity.foundation/didcomm-messaging/spec/#ecdh-1pu-key-wrapping-and-common-protected-headers. Our Aries Framework Go has this implemented [here](https://github.com/hyperledger/aries-framework-go/blob/6041c17d6e599a8000eb546fd8ab9a5189e598af/pkg/doc/jose/encrypter.go#L266-L300). I believe other languages support for 1PU do exist or are in the process of being developed.

However, since DIDComm V2 requires the agents to be authenticated (via means of already known public DIDs), the 1PU is the only viable option in the protocol. Therefore APU/APV recipient headers are mandatory. I'll submit a pr to the DIDComm V2 spec to clarify this point since having both Authcrypt and Anoncrypt support in the spec does not tell why Authcrypt is required.

One can still use ECDH-ES for Anoncrypt requests, but it's not warranted to trigger subsequent DIDComm V2 calls.

**Comment by dhh1128** [comment]
@Baha-sk : you mentioned that you'd submit a PR to clarify this point. Can you possibly do this immediately? We want to close out the final issues on the spec by this coming Monday... If not, can you simply suggest an approximation of what you'd say, and where, and I'll turn it into a PR?

**Comment by Baha-sk** [comment]
thanks for the reminder @dhh1128, this comment fell under the cracks.

#380 created to address this issue.
