### ISSUE TITLE
DID Exchange Protocol 2.0

### ISSUE THREAD

**Issue by apelt** [decentralized-identity/didcomm-messaging#346]
There is only [DID Exchange Protocol 1.0](https://github.com/hyperledger/aries-rfcs/blob/main/features/0023-did-exchange/README.md) compliant with DIDComm v1, but there is no **DID Exchange Protocol 2.0** compliant with DIDComm v2. Will you add this or is it replaced by some different protocol?

It is needed for [did:peer connection establishment](https://identity.foundation/peer-did-method-spec/#didcomm-approach), probably also for did:keri and others.

Other [protocols](https://didcomm.org/search/?q=Protocol&page=1) for starting communication are already updated, including [Out of Band Protocol 2.0](https://didcomm.org/out-of-band/2.0/) which is compliant with DIDComm v2. 

**UPDATE: see comment**

**Comment by apelt** [comment]
Please see **Note** in [#347](https://github.com/decentralized-identity/didcomm-messaging/issues/347#issuecomment-1077364836). The _DID Exchange Protocol 2.0_ might not bee needed if the logic there is OK.

**Comment by TelegramSam** [comment]
The DID Exchange protocol is gone by design. The protocol carries everything needed to create a connection in each message, making an explicit handshake protocol redundant. Instead of first engaging in a handshake protocol, you just send a meaningful message to the other party, and they respond likewise according to whatever protocol is being used.
