### ISSUE TITLE
DID Rotation

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/didcomm-messaging#55]
I wrote the following first as a PR to the Message Structure section of the spec, but I've moved this here to help the conversation. 

An obvious need for this is the ability to pass an initial message in the clear (in a QR code, for example) using something like did:key, and then replace that ephemeral DID with one of another method. 

I also think that the ability to move from one DID method to another is another common use case.

DID rotation is both simple and complex: Some basic, common cases are easy to understand, and some edge cases have really complex side effects.

The text I had in the PR:

----
When the sender is rotating their _from_ DID, additional fields are required to link the new did (present in **from**) and the prior DID:

- **from_prior**: The previously used DID.
- **from_provenance**: The signature of the new **from** DID with an authorized key of the DID in **from_prior**. 

TODO: Define the format of the from_provenance attribute. JWT? 

This method is only needed when moving from one DID to another. Updating a DID should be performed according to the DID method update procedure. 

----

**Comment by kdenhartog** [comment]
Would be good to take into consideration the start of authority problems mentioned in the did core spec and the equivId parameters being discussed over there as well.

In general, I find the idea of this likely quite useful, but find myself unsure what the best method to implement this would be. This is certainly a viable option, but I’m left wondering what limitations we’d need to set around which keys can be used to sign and link two dids. Additionally, I’m not certain it’s valuable to elevate this to the attribute later of a JWM rather than handling it in the body of a message. Likewise maybe we should just be handling this at the did later with equivId or with VCs as a format to assert a variety of identity binding related attributes.

Another angle to the problem which John Jordan mentioned at IIW was there’s a new way to look at the problem which is that the ability to build up and tear down an identity is far easier with an automated system with digital signatures. This leads to the idea he alluded to that maybe it’s advantageous for us to look at the problem as one where identities should be built up and burnt down frequently rather than trying to solve it from the perspective of long lived identifiers that are transferred when circumstances necessitate.

I tend to like that idea quite a bit because it plays well with the privacy principles we’re after as well as shifts the incentives around identity theft to be more time consuming and less valuable for attackers potentially reducing the frequency and impact of identity theft.

Additionally I’m aiming to optimize a solution around 3 core principles.

1 simplicity of state management. - We’ve already got tons of dids and keys going around so new ones aren’t that burdensome. However the requirements to maintain this functionality I suspect will increase complexity around knowing which keys and dids should be used at different times and I’d like to avoid that if possible. We’ve already have a tough problem in front of us, let’s not make it more difficult.

2. Keep edge cases to a minimum - I suspect that the value of this will introduce many new lines of thinking. Some will be useful core features that feel like we absolutely need, and others will be “nice to haves” which will make implementations more complex I suspect. Let’s try to keep this to a minimum if possible because many of them will be solved with methods other than what we decide here because they’re easier. In particular, I’m thinking about cases like proving ownership over multiple dids will likely be easier in the did document or through the use of OCAP style VCs.

3. Robustness - given this feature will inevitably bump up against privacy considerations let’s make sure we’re properly choosing which layer we want to implement this at. A mix of multiple layers will make this far less robust because we’ll need to guarantee the usage of all layers in order to achieve this feature. For example, a solution that relies on a VC being in the body, this JWM attribute being included, and verifying the equivId in the did document would be a solution I would be against. While all pieces are first class citizens in DIDComm, I’d guess if we’d go down this path then we’d likely be walking developers towards messy, intermingled, spaghetti code implementations that are hard to maintain.

With all my thoughts on the table now, I’m looking forward to see where we go with this. Thanks Sam for bringing it up!

**Comment by TelegramSam** [comment]
Rapidly setting up new identities actually promotes the need to support something like **from_prior** to allow existing relationships to rapidly switch to the new identity. 

Relying on external linking between DIDs would eliminate the need for **from_provenance**, but I'm not sure that is the right answer. It may not be desirable to publish the move in a way that is observable by a third party.

And I agree with the core principles you articulate.

**Comment by dhh1128** [comment]
I think that "DID rotation" is too narrow of a framing. Alice should be able to tell Bob, "Hey, Bob, here's another DID I want you to use for me in our relationship" WITHOUT implying that she's abandoning her old one. This is more or less the technical equivalent of a person saying to their friend, "Hey, you've been using my work phone number. Here's my personal number as well." As a separate decision, Alice should also be able to say to Bob, "Please stop using my old DID." A common operation would be to combine these two operations (use new, stop using old) into a DID rotation -- but whatever process we come up with should allow these to be separated in time.

**Comment by dhh1128** [comment]
The reason I think we need this flexibility is that I anticipate it being helpful when we're building and maintaining n-wise relationships with N > 2. This tolerates messiness like Alice and Bob starting out as a pairwise relationship (business partners), and adding a third partner later. When the third partner is added, Alice and Bob can add a new DID for the relationship, and then deprecate the old one over time.

**Comment by TelegramSam** [comment]
I agree with the long term needs for this type of interaction. I'm also interested in the short term need of moving from did:key: to another did method. Is there a way to solve the short term without fouling or complicating the long term?

**Comment by dhh1128** [comment]
One trivial way is to just start using did:peer when you're ready to rotate. Per the recently merged PR to the peer DID spec, did:key:*suffix* is a synonym for (equivalent to) did:peer:0*suffix*. So you can declare a did:key, and when you want to change the keys it uses, you can simply starting treating it as did:peer. There is no need to fetch a new DID doc, do different resolution, or wonder what the did means; it means exactly what it meant when it had the did:key prefix -- except that now you can rotate keys per the did:peer spec (using the state sync protocol), if you want. Wallets and the universal resolver should add a feature to treat these things as synonyms.

A second straightforward method would be to invent a protocol for adding DIDs to a relationship, and removing DIDs. This wouldn't be hard, either.

But what I think you're asking for is a way to: A) not use a protocol, but instead message headers; B) use any arbitrary DID method as the target of rotation. Neither of my suggestions does both of these things. I don't resonate with the aversion to using a protocol. Protocols are the major value-add of DIDComm; DIDComm without them is mostly missing the point. But perhaps I'm missing something about why this is compelling?

**Comment by swcurran** [comment]
I don't get the point of did:peer with no endpoint.  What would be the purpose of did:peer if the peer can't send a message to you?

**Comment by TelegramSam** [comment]
I've written up an alternative approach to using headers. Markdown here, and I will plan to present on this during our Monday meeting.
https://hackmd.io/aiHIFcRZRzyE7Gm6J28grw

**Comment by TelegramSam** [comment]
I've made this back into a better PR: https://github.com/decentralized-identity/didcomm-messaging/pull/59

**Comment by TelegramSam** [comment]
PR was merged.
