### ISSUE TITLE
DID method support and other lower layer metadata 

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/didcomm-messaging#82]
How do I know that the _other_ party supports my DIDComm capabilities? For example:
- DID methods
- Transports
- DIDComm version

Or conversely, how do I find out that my message couldn't be received/processed due to incompatibility of these capabilities?

**Comment by OR13** [comment]
There are lots of aries RFCs that touch on this... https://github.com/hyperledger/aries-rfcs/search?q=discovery&unscoped_q=discovery

I would love if there was a single source of truth, answer to this.

**Comment by kdenhartog** [comment]
Given the asynchronous nature of the protocol some of these aren't going to have great answers to these questions. In general though we've got two main mitigation strategies to help us fail gracefully.

1. Expiration times
2. [Standard Error messaging codes](https://github.com/decentralized-identity/didcomm-messaging/issues/83)

For strategy one, you'd want to use this in the case where it's first message (because you're not sure you're sending it to the right place) and in cases where you have no certainty that everything is setup properly. 

For strategy two, this would be likely be used in cases where a connection has been established already and there's some form of on going messaging continuity. 

I'm not certain if there's other methods that we can use in this case, but I'll take a look through other UDP based protocols and see what they've come up with.

**Comment by TelegramSam** [comment]
Discussed in WG 20211101. Did add accept to OOB invitations. Discover features may also help.

**Comment by TelegramSam** [comment]
Any updates to this @troyronda and @kdenhartog ?

**Comment by TelegramSam** [comment]
Closed after Discussion WG 20220110. Please reopen if you disagree.
