### ISSUE TITLE
What if V2 didn't have AnonCrypt?

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/didcomm-messaging#92]
In DIDComm V1, we have Authcrypt and Anoncrypt. Anoncrypt follows much the same form as Authcrypt, but instead of a known sender key, an ephemeral key is used. With peer DIDs being easy to create, an Authcrypt message using a peer did is basically equivalent to an Anoncrypt message.

If they are equivalent, why don't we eliminate Anoncrypt as an option in V2, for the benefit of simplicity?

**Comment by bumblefudge** [comment]
I feel like opining on this issue is way above my paygrade (and experience level with Indy) but this might be a good question to bring up at multiple sessions of the Interopathon this week?

**Comment by tmarkovski** [comment]
I'm for this. I would even propose that spec defines alternative encryption methods, symmetric encryption based on DID Doc key agreement keys, and even a non-encryption scheme.

**Comment by kdenhartog** [comment]
I think this should be fine to do, but I want to spend a bit more time mulling it over to make sure I'm not missing any edge cases.

> symmetric encryption based on DID Doc key agreement keys
Yes, please this optimization would be useful.

> and even a non-encryption scheme
Do you mean like just sending a plaintext JWM message which isn't signed either?

**Comment by tmarkovski** [comment]
> Do you mean like just sending a plaintext JWM message which isn't signed either?

Yes. Can be used for discovery or any non-privacy/system services. I think the most important aspect would be that the protocol will allow more flexibility over how underlying services can be built around didcomm, and not restrict to a pariwise relationship/channel.

**Comment by kdenhartog** [comment]
Because a signed message isn't restricted to a specific audience in theory I don't think it would be restricted. However, the type of DID used would impact this (e.g. must be a anywise did for it to not restrict to a pairwise channel). Let me have a bit of a think on this more.

The one part that causes some concerns for me is the lack of integrity guarantees on the message which would then likely have to be covered by the transport layer. By sticking with signed, public messages we at least get to keep the integrity protection. Maybe we can use a MAC here instead if we don't care about the message creator? In any case, I'd like to understand the use cases around this better and see if we can find a good answer for it.

@TelegramSam would it be possible to get this issue on the agenda next week?

**Comment by TelegramSam** [comment]
PR Needed to affect the document.
